version: '3.9'

x-spark-common:
  &spark-common
  image: bitnami/spark:${SPARK_VERSION}
  volumes:
    - ./../../spark/jobs:/opt/bitnami/spark/jobs
    - ./../../spark/configs:/opt/bitnami/spark/configs
    - ./../../spark/dependencies:/opt/bitnami/spark/dependencies
    - ./../../spark/tests:/opt/bitnami/spark/tests
    - ./../../spark/packages.zip:/opt/bitnami/spark/packages.zip
  env_file:
    - ./.env
  platform: linux/amd64
  networks:
    - ${GLOBAL_NETWORK:-services}

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "9090:8080"
  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 3g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 3g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-worker-3:
    <<: *spark-common
    container_name: spark-worker-3
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 3g
      SPARK_MASTER_URL: spark://spark-master:7077