version: '3.9'

services:
  ofelia:
    image: mcuadros/ofelia:${OFELIA_VERSION}
    container_name: ofelia
    environment:
      TZ: ${TIME_ZONE}
    depends_on:
      - redis
    command: daemon --config=/etc/ofelia/config.ini
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock:ro
      - ./scripts/ofelia/ofelia_config.ini:/etc/ofelia/config.ini:rw
    networks:
      - ${GLOBAL_NETWORK:-services}