version: '3.9'

services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${REDIS_HOST_NAME}
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_HOST_INTERNAL_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    networks:
      - ${GLOBAL_NETWORK:-services}