version: '3.9'

services:
  redis:
    build:
      context: .
      dockerfile: Redis_dockerfile
    container_name: ${REDIS_HOST_NAME}
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_HOST_INTERNAL_PORT}"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./redis-init.sh:/docker-entrypoint-initdb.d/redis-init.sh
      - ./../../projects/redis-store/redis-backup-pipeline/scripts:/redis-backup/scripts
#      - ./../../projects/redis-store/redis-restore-pipeline/scripts:/redis-restore/scripts
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    networks:
      - ${GLOBAL_NETWORK:-services}